[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18.20.8"

# Asset caching
[[headers]]
  for = "/**/*.@(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.@(js|css|woff2)"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

# Optional security headers (kept)
[[headers]]
  for = "/*"
  [headers.values]
  Permissions-Policy = "camera=(), microphone=(), geolocation=()"
  Referrer-Policy = "strict-origin-when-cross-origin"
  X-Content-Type-Options = "nosniff"
  X-Frame-Options = "DENY"
  X-XSS-Protection = "1; mode=block"