[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"

[[headers]]
  for = "/**/*.@(png|jpg|jpeg|gif|webp|svg)"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/**/*.@(js|css|woff2)"
  [headers.values]
  Cache-Control = "public, max-age=31536000, immutable"